name: travaux_nlp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.3.1=py311h06a4308_0
  - aiodns=3.5.0=py311h06a4308_1
  - aiohappyeyeballs=2.6.1=py311h06a4308_0
  - aiohttp=3.13.3=py311h47b2149_0
  - aiosignal=1.4.0=py311h06a4308_0
  - annotated-types=0.6.0=py311h06a4308_1
  - anyio=4.10.0=py311h06a4308_0
  - aom=3.12.1=h7934f7d_0
  - argon2-cffi=25.1.0=py311h06a4308_0
  - argon2-cffi-bindings=25.1.0=py311hee96239_0
  - arrow-cpp=21.0.0=hb2ad71a_2
  - asttokens=3.0.0=py311h06a4308_0
  - astunparse=1.6.3=py_0
  - async-lru=2.0.5=py311h06a4308_0
  - atk-1.0=2.38.0=he149ff8_0
  - attrs=25.4.0=py311h06a4308_2
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=h3ff94e8_1
  - aws-c-common=0.12.4=hb25bd0a_0
  - aws-c-compression=0.3.1=hb25bd0a_2
  - aws-c-event-stream=0.5.6=hb25bd0a_0
  - aws-c-http=0.10.4=hb25bd0a_0
  - aws-c-io=0.21.4=h3eb0749_0
  - aws-c-mqtt=0.13.3=hb25bd0a_0
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=hb25bd0a_1
  - aws-checksums=0.2.7=hb25bd0a_1
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - babel=2.17.0=py311h06a4308_0
  - beautifulsoup4=4.14.3=py311h06a4308_0
  - blas=1.0=mkl
  - bleach=6.3.0=py311h06a4308_0
  - bottleneck=1.4.2=py311haa0f9ac_1
  - brotlicffi=1.2.0.0=py311h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hd44998d_0
  - ca-certificates=2025.12.2=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - catalogue=2.0.10=py311h06a4308_0
  - certifi=2026.01.04=py311h06a4308_0
  - cffi=2.0.0=py311h4eded50_1
  - charset-normalizer=3.4.4=py311h06a4308_0
  - click=8.2.1=py311h06a4308_1
  - cloudpathlib=0.16.0=py311h06a4308_1
  - cloudpickle=3.1.2=py311h06a4308_0
  - colorama=0.4.6=py311h06a4308_0
  - comm=0.2.3=py311h06a4308_0
  - confection=0.1.5=py311he3bba80_0
  - contourpy=1.3.3=py311hdb19cb5_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - cycler=0.12.1=py311h06a4308_0
  - cymem=2.0.11=py311hbdd6827_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - cython=3.2.2=py311h47b2149_0
  - cython-blis=0.7.9=py311hf4808d0_0
  - datasets=4.4.1=py311h06a4308_1
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.16=py311hbdd6827_1
  - decorator=5.2.1=py311h06a4308_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.4.0=py311h06a4308_0
  - executing=2.2.1=py311h06a4308_0
  - expat=2.7.4=h7354ed3_0
  - filelock=3.20.3=py311h06a4308_0
  - flatbuffers=24.3.25=h6a678d5_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.61.0=py311h47b2149_0
  - freetype=2.14.1=hf5b9546_0
  - fribidi=1.0.16=h9fb5f84_0
  - frozenlist=1.8.0=py311hbdd6827_0
  - fsspec=2025.10.0=py311h7040dfc_0
  - gast=0.7.0=pyhd3eb1b0_0
  - gdk-pixbuf=2.42.10=h64b468e_2
  - gettext=0.21.0=hedfda30_2
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=h5eee18b_0
  - glib=2.86.3=h617169b_0
  - glib-tools=2.86.3=h9fad118_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.2=py311ha78e65c_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h78213b7_2
  - grpcio=1.74.1=py311hca1084e_0
  - gtk2=2.24.33=h4ce724d_4
  - gts=0.7.6=hb67d8dd_3
  - h11=0.16.0=py311h06a4308_1
  - h5py=3.15.1=py311hea18c50_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.5=h2b7332f_2
  - hf-xet=1.2.0=py311h8c4cd34_0
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py311h06a4308_0
  - httpx=0.28.1=py311h06a4308_1
  - huggingface_hub=0.34.4=py311h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.11=py311h06a4308_0
  - importlib-metadata=8.7.0=py311h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=6.31.0=py311h7040dfc_0
  - ipython=9.7.0=py311h06a4308_0
  - ipython_pygments_lexers=1.1.1=py311h06a4308_0
  - ipywidgets=8.1.7=py311h06a4308_0
  - jansson=2.14=h5eee18b_1
  - jedi=0.19.2=py311h06a4308_0
  - jinja2=3.1.6=py311h06a4308_0
  - joblib=1.5.3=py311h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - json5=0.12.1=py311h06a4308_0
  - jsonschema=4.25.1=py311h06a4308_0
  - jsonschema-specifications=2025.9.1=py311h06a4308_0
  - jupyter=1.1.1=py311h06a4308_0
  - jupyter-lsp=2.3.0=py311h06a4308_0
  - jupyter_client=8.8.0=py311h06a4308_0
  - jupyter_console=6.6.3=py311h06a4308_0
  - jupyter_core=5.9.1=py311h06a4308_0
  - jupyter_events=0.12.0=py311h06a4308_1
  - jupyter_server=2.17.0=py311h06a4308_1
  - jupyter_server_terminals=0.5.4=py311h06a4308_0
  - jupyterlab=4.5.3=py311h06a4308_1
  - jupyterlab_pygments=0.3.0=py311h06a4308_0
  - jupyterlab_server=2.28.0=py311h06a4308_1
  - jupyterlab_widgets=3.0.16=py311h06a4308_0
  - keras=3.13.2=py311hfbdd2b3_0
  - kiwisolver=1.4.9=py311h24d9097_0
  - langcodes=3.5.0=py311h06a4308_0
  - language-data=1.3.0=py311h06a4308_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250814.1=cxx17_h7c8e02e_0
  - libavif=1.3.0=h3539ee5_0
  - libboost=1.88.0=h9d9b81f_0
  - libbrotlicommon=1.2.0=h32cd6e7_0
  - libbrotlidec=1.2.0=ha2c5f68_0
  - libbrotlienc=1.2.0=h2e96acb_0
  - libcups=2.4.15=hbe4054b_0
  - libcurl=8.17.0=hc93bc37_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgd=2.3.3=h536bbd8_4
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.86.3=h8b17d9a_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libgrpc=1.74.1=ha2a6211_0
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm15=15.0.7=he89c38a_4
  - libltdl=2.6.0=h47b2149_0
  - libnghttp2=1.67.1=h697f920_0
  - libnsl=2.0.0=h5eee18b_0
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.54=hee55ce4_0
  - libpq=17.6=ha51bf15_0
  - libprotobuf=6.33.0=h8e73247_1
  - libre2-11=2025.11.05=h3218f0b_0
  - librsvg=2.56.3=hb0330b6_2
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libthrift=0.22.0=hd8eb582_0
  - libtiff=4.7.1=h029b1ac_0
  - libtool=2.6.0=h7354ed3_0
  - libtorch=2.7.0=cpu_mkl_h2ed035f_101
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp=1.6.0=h089d785_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - marisa-trie=1.3.1=py311hbdd6827_0
  - markdown=3.10=py311h06a4308_0
  - markdown-it-py=2.2.0=py311h06a4308_1
  - markupsafe=3.0.2=py311h5eee18b_0
  - matplotlib=3.10.8=py311h06a4308_0
  - matplotlib-base=3.10.8=py311h8a257da_0
  - matplotlib-inline=0.2.1=py311h06a4308_0
  - mdurl=0.1.2=py311h06a4308_0
  - mesalib=25.1.5=h31e3550_0
  - mistune=3.1.2=py311h06a4308_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py311hacdc0fc_0
  - mkl_fft=2.1.1=py311h8fe796d_0
  - mkl_random=1.3.0=py311h505adc9_0
  - ml_dtypes=0.5.4=py311h23c847b_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpi=1.0=mpich
  - mpi4py=4.0.3=py311ha730828_1
  - mpich=4.3.2=hf345156_0
  - mpmath=1.3.0=py311h06a4308_0
  - multidict=6.7.0=py311hee96239_0
  - multiprocess=0.70.18=py311h06a4308_1
  - murmurhash=1.0.15=py311h7149228_0
  - mysql-common=9.3.0=h9e076cb_4
  - mysql-libs=9.3.0=h6ecde68_4
  - namex=0.1.0=py311h06a4308_0
  - nbclient=0.10.2=py311h06a4308_0
  - nbconvert=7.16.6=py311h06a4308_0
  - nbconvert-core=7.16.6=py311h06a4308_0
  - nbconvert-pandoc=7.16.6=py311h06a4308_0
  - nbformat=5.10.4=py311h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - networkx=3.6.1=py311h06a4308_0
  - nltk=3.9.2=py311h19f43ea_0
  - notebook=7.5.3=py311h06a4308_0
  - notebook-shim=0.2.4=py311h06a4308_1
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - numexpr=2.14.1=py311h41d4191_0
  - numpy=1.26.4=py311h64c44e4_1
  - numpy-base=1.26.4=py311he1678cf_1
  - openjpeg=2.5.4=h4e0627c_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.0.19=h1b28b03_0
  - opentelemetry-api=1.38.0=py311h06a4308_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optree=0.18.0=py311h24d9097_0
  - orc=2.2.0=h13e6d3f_1
  - overrides=7.7.0=py311h06a4308_0
  - packaging=25.0=py311h06a4308_1
  - pandas=2.3.3=py311h23c847b_1
  - pandoc=3.8=h06a4308_0
  - pandocfilters=1.5.1=py311h06a4308_0
  - pango=1.50.7=h668f713_2
  - parso=0.8.5=py311h06a4308_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=py311h06a4308_1
  - pillow=12.0.0=py311h3b88751_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=py311h06a4308_0
  - poppler=24.09.0=h696634e_4
  - poppler-data=0.4.12=h06a4308_0
  - preshed=3.0.12=py311h7354ed3_0
  - prometheus_client=0.21.1=py311h06a4308_0
  - prompt-toolkit=3.0.52=py311h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - propcache=0.4.1=py311h47b2149_0
  - protobuf=6.33.0=py311hbdd6827_0
  - psutil=7.0.0=py311hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py311h06a4308_0
  - pyarrow=21.0.0=py311h86c3e14_1
  - pycares=4.10.0=py311ha137689_0
  - pycparser=2.23=py311h06a4308_0
  - pydantic=1.10.19=py311h5eee18b_0
  - pydantic-core=2.41.5=py311h498d7c9_1
  - pydot=3.0.4=py311h06a4308_0
  - pygments=2.19.2=py311h06a4308_0
  - pyparsing=3.2.5=py311h06a4308_0
  - pyqt=6.9.1=py311hc79087c_0
  - pyqt6-sip=13.10.2=py311hee96239_0
  - pysocks=1.7.1=py311h06a4308_1
  - python=3.11.14=h6fa692b_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-fastjsonschema=2.21.2=py311h06a4308_0
  - python-flatbuffers=24.3.25=py311h06a4308_0
  - python-json-logger=4.0.0=py311h06a4308_0
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py311h5eee18b_0
  - pytorch=2.7.0=cpu_mkl_py311ha2f9cfc_102
  - pytz=2025.2=py311h06a4308_0
  - pyyaml=6.0.3=py311h591646f_0
  - pyzmq=27.1.0=py311hcf8288c_1
  - qtbase=6.9.2=hd13baf8_5
  - qtconsole=5.7.0=py311h06a4308_0
  - qtdeclarative=6.9.2=h55666de_1
  - qtpy=2.4.3=py311h06a4308_0
  - qtsvg=6.9.2=h75a08ff_1
  - qttools=6.9.2=hc856bc8_1
  - qtwayland=6.9.2=h9f1b7ec_1
  - qtwebchannel=6.9.2=hbdd6827_1
  - qtwebsockets=6.9.2=hbdd6827_1
  - re2=2025.11.05=h6b3e72e_0
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=py311h06a4308_0
  - regex=2025.11.3=py311h47b2149_0
  - requests=2.32.5=py311h06a4308_1
  - rfc3339-validator=0.1.4=py311h06a4308_0
  - rfc3986-validator=0.1.1=py311h06a4308_0
  - rich=13.9.4=py311h06a4308_0
  - rpds-py=0.28.0=py311h498d7c9_0
  - ruamel_yaml=0.17.21=py311h5eee18b_0
  - s2n=1.5.14=hdbd6064_0
  - safetensors=0.6.2=py311h498d7c9_0
  - scikit-learn=1.8.0=py311h86c3e14_0
  - scipy=1.16.3=py311h33bc11c_0
  - send2trash=1.8.3=py311h06a4308_0
  - setuptools=80.10.2=py311h06a4308_0
  - shellingham=1.5.4=py311h06a4308_0
  - sip=6.12.0=py311h7934f7d_0
  - six=1.17.0=py311h06a4308_0
  - sleef=3.5.1=h5eee18b_2
  - smart_open=5.2.1=py311h06a4308_0
  - snappy=1.2.2=h4bcf44c_1
  - sniffio=1.3.1=py311h06a4308_0
  - soupsieve=2.5=py311h06a4308_0
  - spacy=3.7.2=py311h4cb112f_0
  - spacy-alignments=0.9.2=py311hd71b016_0
  - spacy-legacy=3.0.12=py311h06a4308_0
  - spacy-loggers=1.0.5=py311h06a4308_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.51.1=he0a8d7e_0
  - srsly=2.5.2=py311h7354ed3_0
  - stack_data=0.6.3=py311h06a4308_0
  - sympy=1.14.0=py311h06a4308_1
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - tensorboard=2.20.0=py311h06a4308_0
  - tensorboard-data-server=0.7.0=py311h52d8a92_1
  - tensorflow=2.20.0=cpu_py311hbca4264_1
  - tensorflow-base=2.20.0=cpu_py311h1076484_1
  - termcolor=3.2.0=py311h06a4308_0
  - terminado=0.18.1=py311h06a4308_1
  - tf-keras=2.20.1=py311h06a4308_0
  - thinc=8.2.2=py311h4cb112f_0
  - threadpoolctl=3.5.0=py311h7040dfc_1
  - tinycss2=1.4.0=py311h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tokenizers=0.19.1=py311h585d796_0
  - torchvision=0.15.2=cuda118py311h4cc2eb7_0
  - tornado=6.5.4=py311h47b2149_0
  - tqdm=4.67.1=py311h7040dfc_1
  - traitlets=5.14.3=py311h06a4308_0
  - transformers=4.41.2=py311h06a4308_0
  - typer=0.9.0=py311h06a4308_0
  - typer-slim=0.20.0=py311h06a4308_0
  - typing-extensions=4.15.0=py311h06a4308_0
  - typing-inspection=0.4.2=py311h06a4308_0
  - typing_extensions=4.15.0=py311h06a4308_0
  - tzdata=2025c=he532380_0
  - ujson=5.11.0=py311hbdd6827_0
  - urllib3=2.6.3=py311h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - uvloop=0.22.1=py311h939ff40_1
  - wasabi=1.1.3=py311h06a4308_0
  - wayland=1.24.0=hdac8c69_0
  - wcwidth=0.2.14=py311h06a4308_0
  - weasel=0.3.4=py311h06a4308_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=1.8.0=py311h06a4308_0
  - werkzeug=3.1.3=py311h06a4308_0
  - wheel=0.46.3=py311h06a4308_0
  - widgetsnbextension=4.0.14=py311h06a4308_0
  - wordcloud=1.9.5=py311h44c8d7b_0
  - wrapt=2.0.1=py311h47b2149_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.22.0=py311hee96239_0
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=py311h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - en-core-web-md==3.7.1
      - en-core-web-sm==3.7.1
      - fr-core-news-md==3.7.0
      - fr-core-news-sm==3.7.0
      - textblob==0.19.0
prefix: /home/paisible/miniconda3/envs/travaux_nlp
